document.addEventListener("DOMContentLoaded",function(){const stickyWallView=document.getElementById("sticky-wall-view");const calendarView=document.getElementById("calendar-view");const profileView=document.getElementById("profile-view");const stickyWallLink=document.getElementById("sticky-wall-link");const calendarLink=document.getElementById("calendar-link");const profileLink=document.getElementById("profile-link");const userNicknameSpan=document.getElementById("user-nickname");const mobileMenuBtn=document.getElementById("mobile-menu-btn");const sidebar=document.getElementById("sidebar");const closeSidebarBtn=document.getElementById("close-sidebar");const sidebarOverlay=document.getElementById("sidebar-overlay");const modal=document.getElementById("add-note-modal");const addNoteForm=document.getElementById("add-note-form");const cancelNoteBtn=document.getElementById("cancel-note");const colorSelectors=document.querySelectorAll('input[name="note-color"]');const profileForm=document.getElementById("profile-form");function toggleMobileMenu(){if(sidebar.classList.contains("-translate-x-full")){sidebar.classList.remove("-translate-x-full");sidebarOverlay.classList.remove("hidden")}else{sidebar.classList.add("-translate-x-full");sidebarOverlay.classList.add("hidden")}}
if(mobileMenuBtn){mobileMenuBtn.addEventListener("click",toggleMobileMenu)}
if(closeSidebarBtn){closeSidebarBtn.addEventListener("click",toggleMobileMenu)}
if(sidebarOverlay){sidebarOverlay.addEventListener("click",toggleMobileMenu)}
const calendarGrid=document.getElementById("calendar-grid");const monthYearDisplay=document.getElementById("month-year");const prevMonthBtn=document.getElementById("prev-month");const nextMonthBtn=document.getElementById("next-month");let currentDate=new Date();const colorClasses={yellow:"bg-yellow-200 text-gray-800",pink:"bg-pink-200 text-gray-800",orange:"bg-orange-200 text-gray-800",blue:"bg-blue-200 text-gray-800",};function switchView(viewToShow){if(sidebar&&!sidebar.classList.contains("-translate-x-full")&&window.innerWidth<768){toggleMobileMenu()}[stickyWallView,calendarView,profileView].forEach((view)=>{if(view)view.classList.add("hidden");});if(viewToShow)viewToShow.classList.remove("hidden");[stickyWallLink,calendarLink,profileLink].forEach((link)=>{if(link){link.classList.remove("bg-white/10","text-white");link.classList.add("text-gray-400","hover:bg-white/5","hover:text-white");const icon=link.querySelector("i");if(icon){}}});if(viewToShow===stickyWallView&&stickyWallLink){stickyWallLink.classList.remove("text-gray-400","hover:bg-white/5");stickyWallLink.classList.add("bg-white/10","text-white")}else if(viewToShow===calendarView&&calendarLink){calendarLink.classList.remove("text-gray-400","hover:bg-white/5");calendarLink.classList.add("bg-white/10","text-white")}else if(viewToShow===profileView&&profileLink){profileLink.classList.remove("text-gray-400","hover:bg-white/5");profileLink.classList.add("bg-white/10","text-white")}}
async function fetchNotes(){try{const response=await fetch("service/notes.php");if(!response.ok)throw new Error("Network response was not ok");const notes=await response.json();renderNotes(notes)}catch(error){console.error("Fetch error:",error)}}
function renderNotes(notes){const wall=document.getElementById("sticky-wall");if(!wall)return;wall.innerHTML="";if(notes.length===0){const emptyStateMessage=document.createElement("div");emptyStateMessage.className="col-span-full text-center text-gray-400 py-10 rounded-xl bg-white/5 border border-white/5";emptyStateMessage.innerHTML=`
                <h3 class="text-xl font-semibold mb-2">${TRANSLATIONS.no_notes}</h3>
                <p class="text-sm">${TRANSLATIONS.click_plus}</p>
            `;wall.appendChild(emptyStateMessage)}else{notes.forEach((note)=>{const noteEl=createNoteElement(note);wall.appendChild(noteEl)})}
const addCard=document.createElement("div");addCard.className="bg-white/5 border-2 border-dashed border-white/20 rounded-xl p-6 flex items-center justify-center min-h-[220px] cursor-pointer hover:bg-white/10 hover:border-white/40 transition-all group";addCard.innerHTML='<span class="text-5xl font-thin text-gray-500 group-hover:text-white transition-colors">+</span>';addCard.addEventListener("click",()=>{if(modal)modal.classList.remove("hidden");});wall.appendChild(addCard)}
function createNoteElement(note){const noteEl=document.createElement("div");noteEl.className=`${
      colorClasses[note.color] || "bg-yellow-200 text-gray-800"
    } rounded-xl p-6 flex flex-col min-h-[220px] group relative shadow-lg transform hover:-translate-y-1 transition-all duration-300`;let tasksHtml=note.tasks.map((task)=>`<li data-task-id="${
            task.id
          }" class="task-item cursor-pointer flex items-center gap-2 ${
            task.is_completed ? "completed opacity-50 line-through" : ""
          }">
                <i class="fa-${
                  task.is_completed
                    ? "solid fa-circle-check"
                    : "regular fa-circle"
                } text-sm"></i>
                <span>${task.content}</span>
            </li>`).join("");noteEl.innerHTML=`
            <h3 class="font-bold text-lg mb-3 tracking-tight">${note.title}</h3>
            <ul class="space-y-2 flex-grow overflow-y-auto max-h-[160px] custom-scroll">${tasksHtml}</ul>
            <button class="delete-note-btn absolute top-3 right-3 text-gray-600 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-all p-1 rounded-full hover:bg-black/5">
                <i class="fa-solid fa-trash-can"></i>
            </button>
        `;const deleteBtn=noteEl.querySelector(".delete-note-btn");if(deleteBtn){deleteBtn.addEventListener("click",async(e)=>{e.stopPropagation();if(confirm(TRANSLATIONS.delete_confirm)){await deleteNote(note.id);fetchNotes()}})}
noteEl.querySelectorAll(".task-item").forEach((item)=>{item.addEventListener("click",async(e)=>{e.stopPropagation();const taskId=item.dataset.taskId;const isCompleted=!item.classList.contains("completed");const icon=item.querySelector("i");if(isCompleted){item.classList.add("completed","opacity-50","line-through");icon.classList.remove("fa-regular","fa-circle");icon.classList.add("fa-solid","fa-circle-check")}else{item.classList.remove("completed","opacity-50","line-through");icon.classList.remove("fa-solid","fa-circle-check");icon.classList.add("fa-regular","fa-circle")}
await toggleTaskCompletion(taskId,isCompleted)})});return noteEl}
async function deleteNote(noteId){await fetch("service/notes.php",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:noteId}),})}
async function toggleTaskCompletion(taskId,isCompleted){await fetch("service/notes.php",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:taskId,is_completed:isCompleted}),})}
if(addNoteForm){addNoteForm.addEventListener("submit",async function(e){e.preventDefault();const title=document.getElementById("note-title").value;const tasksRaw=document.getElementById("note-tasks").value;const tasks=tasksRaw.split("\n").filter((t)=>t.trim()!=="");const colorInput=document.querySelector('input[name="note-color"]:checked');const color=colorInput?colorInput.value:"yellow";await fetch("service/notes.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,tasks,color}),});if(modal)modal.classList.add("hidden");addNoteForm.reset();const yellowColor=document.querySelector('input[name="note-color"][value="yellow"]');if(yellowColor)yellowColor.checked=!0;fetchNotes()})}
if(cancelNoteBtn){cancelNoteBtn.addEventListener("click",()=>{if(modal)modal.classList.add("hidden");if(addNoteForm)addNoteForm.reset();})}
if(modal){modal.addEventListener("click",(e)=>{if(e.target===modal){modal.classList.add("hidden")}})}
async function loadProfile(){try{const response=await fetch("service/profile.php");if(!response.ok)throw new Error("Failed to fetch profile");const profile=await response.json();const nicknameInput=document.getElementById("profile-nickname");const fullnameInput=document.getElementById("profile-fullname");const ageInput=document.getElementById("profile-age");const dobInput=document.getElementById("profile-dob");if(nicknameInput)nicknameInput.value=profile.nickname||"";if(fullnameInput)fullnameInput.value=profile.fullname||"";if(ageInput)ageInput.value=profile.age||"";if(dobInput)dobInput.value=profile.dob||"";if(userNicknameSpan)
userNicknameSpan.textContent=profile.nickname||TRANSLATIONS.guest}catch(error){console.error("Error loading profile:",error)}}
if(profileForm){profileForm.addEventListener("submit",async function(e){e.preventDefault();const profileData={nickname:document.getElementById("profile-nickname").value,fullname:document.getElementById("profile-fullname").value,age:document.getElementById("profile-age").value,dob:document.getElementById("profile-dob").value,};try{const response=await fetch("service/profile.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(profileData),});if(!response.ok)throw new Error("Failed to save profile");alert(TRANSLATIONS.profile_saved);if(userNicknameSpan)
userNicknameSpan.textContent=profileData.nickname}catch(error){console.error("Error saving profile:",error);alert(TRANSLATIONS.profile_failed)}})}
function renderCalendar(){if(!calendarGrid||!monthYearDisplay)return;calendarGrid.innerHTML="";const month=currentDate.getMonth();const year=currentDate.getFullYear();const monthName=TRANSLATIONS.months[month];monthYearDisplay.textContent=`${monthName} ${year}`;const firstDayOfMonth=new Date(year,month,1).getDay();const daysInMonth=new Date(year,month+1,0).getDate();const dayHeaders=TRANSLATIONS.days_short;dayHeaders.forEach((day)=>{const dayEl=document.createElement("div");dayEl.className="text-center font-bold text-gray-500 text-sm";dayEl.textContent=day;calendarGrid.appendChild(dayEl)});for(let i=0;i<firstDayOfMonth;i++){calendarGrid.appendChild(document.createElement("div"))}
for(let day=1;day<=daysInMonth;day++){const dayEl=document.createElement("div");dayEl.className="text-center py-3 border border-white/5 rounded-xl text-gray-300 hover:bg-white/10 transition-colors cursor-pointer";dayEl.textContent=day;if(day===new Date().getDate()&&month===new Date().getMonth()&&year===new Date().getFullYear()){dayEl.classList.remove("text-gray-300","hover:bg-white/10");dayEl.classList.add("bg-indigo-600","text-white","shadow-lg","shadow-indigo-500/50","border-transparent")}
calendarGrid.appendChild(dayEl)}}
if(prevMonthBtn){prevMonthBtn.addEventListener("click",()=>{currentDate.setMonth(currentDate.getMonth()-1);renderCalendar()})}
if(nextMonthBtn){nextMonthBtn.addEventListener("click",()=>{currentDate.setMonth(currentDate.getMonth()+1);renderCalendar()})}
if(stickyWallLink)
stickyWallLink.addEventListener("click",(e)=>{e.preventDefault();switchView(stickyWallView)});if(calendarLink)
calendarLink.addEventListener("click",(e)=>{e.preventDefault();switchView(calendarView)});if(profileLink)
profileLink.addEventListener("click",(e)=>{e.preventDefault();switchView(profileView)});function init(){switchView(stickyWallView);fetchNotes();loadProfile();renderCalendar()}
init()})
